---
title: "Machine Learning Classification of Infants' Full-Day Movements"
shorttitle: "Classifying Movements"
author:
  - name: John M. Franchak
    corresponding: true
    orcid: 0000-0002-0751-2864
    email: franchak@ucr.edu
    affiliations:
      - name: University of California, Riverside
        department: Department of Psychology
        address: 900 University Avenue
        city: Riverside
        region: CA
        country: USA
        postal-code: 92521
author-note:
  status-changes: 
    affiliation-change: ~
    deceased: ~
  disclosures:
    study-registration: ~
    data-sharing: ~
    related-report: ~
    conflict-of-interest: ~
    financial-support: ~
    gratitude: ~
    authorship-agreements: ~
abstract: "This document is a template."
impact-statement: ~
keywords: [Keyword 1, Keyword 2, Keyword 3]
bibliography: references.bib
format:
  apaquarto-docx: default
  apaquarto-html: default
  apaquarto-pdf:
    documentmode: man
---

Everyday learning inputs—visual experiences, object interactions, and social exchanges—are filtered through infants' motor systems. In this chapter, I focus on two aspects of movement: position and restraint. Position refers to the configuration of the body with respect to gravity, such as lying supine on the back, prone on the stomach (whether stationary or crawling), sitting, or standing upright (whether stationary or walking). Infants' position from moment to moment shapes their view of objects and faces [@LuoFranchak2020; @KretchFranchak2014], constrains how they explore objects in their hands [@SoskaAdolph2014; @KretchMarcinowski2022], and predicts the frequency of adults' speech [@RouseyTang2026]. Restraint refers to infants' opportunity to switch positions [@WangHRousey2026]. When infants are restrained, such as held in a caregiver's arms or strapped into a car seat or high chair, they cannot change positions. When unrestrained, infants can voluntarily switch between positions in their motor skill repertoire. Restraint also shapes everyday learning inputs: Infants have broader views of the environment when carried off the ground [@KretchAdolph2015], but infants have less access to objects [@FranchakKadooka2024] and hear less adult speech when restrained [@MalachowskiSalo2023].

Thus, infants' opportunities for learning depending on how much time they spend in different positions and restraint in everyday life, which vary according to infants' age, motor skill development, and caregiving choices. With age, infants spend less time supine and restrained and spend more time sitting and standing [@KretchLuna2025; @FranchakKadooka2024; @Franchak2019aa; @FranchakRousey2026]. Infants who can sit independently spend more time sitting unrestrained [@KretchLuna2025], and infants who can walk independently spend more time standing upright [@FranchakRousey2026]. Despite these developmental trends, there are considerable individual differences that likely depend on caregiving practices and daily routines. Whereas some caregivers may choose to more often use specialized devices likes swings, jumpers, and exersaucers [@CallahanSisler1997; @KarasikKuchirko2022], others may more often choose to hold infants in their arms or position infants on the floor. Caregivers' choices about daily activities, such as errands and meals, also matter: Infants spend more time restrained when out of the house on errands and during mealtime [@FranchakFord2026].

Consequently, position and restraint are distributed heterogeneously throughout the day [@FranchakRousey2026; @FranchakTang2024]. An hour spent playing might involve a long bout of time unrestrained during which the infant switches between sitting, prone, and standing positions. An hour spent eating a meal might involve a continuous bout of sitting while restrained in a high chair. An hour spent playing, fussing, and nursing could involve frequent switches between laying on the couch, crawling on the floor, and being held in caregivers' arms. This poses a challenge for researchers who wish to measure everyday position and restraint, because sampling any single hour might fail to capture the full variation in movement across a day. Most video observations of infants' home behavior sample 1-2 hours at most [e.g., @HerzbergFletcher2021], meaning that other parts of the daily routine go unobserved. Capturing a full waking day of infants' movements on video would also mean labor-intensive video coding, which could take as many as 5 hours per hour video to annotate [@FranchakTang2024].

Analogous challenge for wearable IMUs. What's been done already. [@AiraksinenRasanen2020].

Chapter focuses on our workflow used in past work focusing on full-day position and restraint [@FranchakTang2024; @KretchEnriques2026; @WangHRousey2026].

# Data Collection

Some past work in the lab. Focus here is in the home. Current limits (driving/strollers).

## Sensor Garment

Interior pockets with closures for safety Accel and gyro Number of sensors Sensor placement Maiju's approach; other work w/ chestworn sensor (Greenspan)

## Capturing Ground Truth Video

Synchronization Amount of data Coverage of positions (e.g. sitting variations) and mix of freeplay

## Full-Day or Multiple-Day Considerations

Capturing data past video recorded portion Nap/wear time logging Sensor drift Show examples of multi-day data

# Data Processing and Model Training

## Extracting Motion Features

Window size Features Accel vs. gyro features (Airaksinen) alignment of motion features to the actual behavior

## Scoring Ground Truth

Synchronization Developing coding scheme is what determines output

# Model Evaluation

Point to general refs about binary and multi-class categorization Project needs dictate what is relevant for evaluation (overall metrics vs. bouts, absolute time vs. relative time, generalization to new exemplars vs. best prediction of current data)

## Training/Testing Partition

Individual models vs. group models and generalization LOOCV examples Sensor CP model composition and size examples

## Evaluation Metrics

Accuracy/kappa Kaya lab paper

Continuous outcomes (Yao) for prevalence predictions Bout structure

# Applications

# References

::: {#refs}
:::
